### ISSUE TITLE
Sprint 3 Feedback (adding more recipes)

### ISSUE THREAD

**Issue by imoon2003** [cis3296f24/project-01-Super-Chef#50]
I suggest having recipes that fulfill multiple filters, specifically with balanced (ex: no recipes for balanced with high protein).

**Comment by magdarogalska** [comment]
You can have recipes that fulfill multiple filters, this specific example doesn't work because you can't have these both requirements fulfilled at once (if something is high protein it can't be balanced by the recipes labels requirements).
